- name: Install haproxy
  apt: name=haproxy

- name: Configure haproxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

- name: Configure haproxy autostart
  copy: src=etc_default_haproxy dest=/etc/default/haproxy

- name: Start the haproxy service
  service: name=haproxy state=started enabled=yes
