- name: Install nginx
  apt: name=nginx

- name: Remove default site
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Configure nginx
  template: src=drupal.conf.j2 dest=/etc/nginx/sites-available/drupal.conf

- name: Enable drupal site
  file: path=/etc/nginx/sites-enabled/drupal state=link src=/etc/nginx/sites-available/drupal.conf
  notify: restart nginx
