- name: Install and Configure Database Cluster
  hosts: percona
  remote_user: ubuntu
  sudo: yes
  roles:
  - base
  - database

- name: Install and Configure Drupal
  hosts: drupal
  remote_user: ubuntu
  sudo: yes
  roles:
  - base
  - cms

- name: Install and Configure Nginx
  hosts: nginx
  remote_user: ubuntu
  sudo: yes
  roles:
  - base
  - nginx

- name: Install and Configure Balancer
  hosts: haproxy
  remote_user: ubuntu
  sudo: yes
  roles:
  - base
  - balancer


